"""Decision Chain MCP Server

为 decision_chain_agent 提供规划文件读写服务：
- Plan 模式: 创建/读取/更新规划文档 (plan.md)
- Spec 模式: 创建/读取/更新规格文档 (spec.md, tasks.md, checklist.md)
- 支持模板化创建
- 支持版本管理
"""

import asyncio
import os
import re
from datetime import datetime

from src.flood_decision_agent.shared.utils.json_utils import fast_json_dumps, fast_json_loads
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from mcp.server import Server
from mcp.types import Tool, TextContent
from mcp.server.stdio import stdio_server


# 创建 MCP Server
server = Server("flood-agent-decision-chain")

# 配置
PLANS_DIR = "./plans"
SPECS_DIR = "./.trae/specs"


def _ensure_dirs():
    """确保目录存在"""
    os.makedirs(PLANS_DIR, exist_ok=True)
    os.makedirs(SPECS_DIR, exist_ok=True)


def _validate_path(path: str, allowed_dirs: List[str]) -> str:
    """验证路径是否在允许范围内"""
    abs_path = os.path.abspath(path)
    for allowed in allowed_dirs:
        if abs_path.startswith(os.path.abspath(allowed)):
            return abs_path
    raise ValueError(f"路径不在允许范围内: {path}")


# ============== 模板定义 ==============

PLAN_TEMPLATE = """# {title}

## 概述

{description}

## 目标

{goals}

## 实施步骤

{steps}

## 验收标准

{criteria}

## 备注

{notes}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""

SPEC_TEMPLATE = """# {title} - 规格文档

## 概述

{description}

## 功能需求

{requirements}

## 技术方案

{technical_design}

## 接口定义

{interfaces}

## 验收标准

{acceptance_criteria}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""

TASKS_TEMPLATE = """# {title} - 任务列表

## 任务分解

{tasks}

## 依赖关系

{dependencies}

## 时间估算

{estimates}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""

CHECKLIST_TEMPLATE = """# {title} - 检查清单

## 前置条件

{prerequisites}

## 开发检查项

{development}

## 测试检查项

{testing}

## 部署检查项

{deployment}

## 文档检查项

{documentation}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""


@server.list_tools()
async def list_tools() -> List[Tool]:
    """定义可用工具"""
    return [
        # Plan 模式工具
        Tool(
            name="create_plan",
            description="创建规划文档 (plan.md)",
            inputSchema={
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "规划标题"
                    },
                    "description": {
                        "type": "string",
                        "description": "规划描述"
                    },
                    "goals": {
                        "type": "string",
                        "description": "目标列表（markdown 格式）"
                    },
                    "steps": {
                        "type": "string",
                        "description": "实施步骤（markdown 格式）"
                    },
                    "criteria": {
                        "type": "string",
                        "description": "验收标准（markdown 格式）"
                    },
                    "notes": {
                        "type": "string",
                        "description": "备注（markdown 格式）",
                        "default": ""
                    },
                    "output_path": {
                        "type": "string",
                        "description": "输出路径，如 ./plans/my_plan.md"
                    }
                },
                "required": ["title", "description", "goals", "steps", "criteria"]
            }
        ),
        Tool(
            name="read_plan",
            description="读取规划文档",
            inputSchema={
                "type": "object",
                "properties": {
                    "plan_path": {
                        "type": "string",
                        "description": "规划文件路径"
                    }
                },
                "required": ["plan_path"]
            }
        ),
        Tool(
            name="update_plan",
            description="更新规划文档",
            inputSchema={
                "type": "object",
                "properties": {
                    "plan_path": {
                        "type": "string",
                        "description": "规划文件路径"
                    },
                    "section": {
                        "type": "string",
                        "description": "要更新的章节，如 '实施步骤'"
                    },
                    "content": {
                        "type": "string",
                        "description": "新内容"
                    }
                },
                "required": ["plan_path", "section", "content"]
            }
        ),
        
        # Spec 模式工具
        Tool(
            name="create_spec",
            description="创建规格文档套装 (spec.md, tasks.md, checklist.md)",
            inputSchema={
                "type": "object",
                "properties": {
                    "feature_name": {
                        "type": "string",
                        "description": "功能名称（用于目录命名）"
                    },
                    "title": {
                        "type": "string",
                        "description": "规格标题"
                    },
                    "description": {
                        "type": "string",
                        "description": "功能描述"
                    },
                    "requirements": {
                        "type": "string",
                        "description": "功能需求（markdown 格式）"
                    },
                    "technical_design": {
                        "type": "string",
                        "description": "技术方案（markdown 格式）"
                    },
                    "interfaces": {
                        "type": "string",
                        "description": "接口定义（markdown 格式）"
                    },
                    "acceptance_criteria": {
                        "type": "string",
                        "description": "验收标准（markdown 格式）"
                    },
                    "tasks": {
                        "type": "string",
                        "description": "任务列表（markdown 格式）"
                    }
                },
                "required": ["feature_name", "title", "description", "requirements"]
            }
        ),
        Tool(
            name="read_spec",
            description="读取规格文档",
            inputSchema={
                "type": "object",
                "properties": {
                    "spec_path": {
                        "type": "string",
                        "description": "规格文件路径"
                    }
                },
                "required": ["spec_path"]
            }
        ),
        Tool(
            name="update_spec",
            description="更新规格文档",
            inputSchema={
                "type": "object",
                "properties": {
                    "spec_path": {
                        "type": "string",
                        "description": "规格文件路径"
                    },
                    "section": {
                        "type": "string",
                        "description": "要更新的章节"
                    },
                    "content": {
                        "type": "string",
                        "description": "新内容"
                    }
                },
                "required": ["spec_path", "section", "content"]
            }
        ),
        
        # 通用工具
        Tool(
            name="list_plans",
            description="列出所有规划文件",
            inputSchema={
                "type": "object",
                "properties": {
                    "limit": {
                        "type": "integer",
                        "description": "最大返回数量",
                        "default": 50
                    }
                }
            }
        ),
        Tool(
            name="list_specs",
            description="列出所有规格文档目录",
            inputSchema={
                "type": "object",
                "properties": {}
            }
        ),
        Tool(
            name="delete_document",
            description="删除文档",
            inputSchema={
                "type": "object",
                "properties": {
                    "doc_path": {
                        "type": "string",
                        "description": "文档路径"
                    }
                },
                "required": ["doc_path"]
            }
        )
    ]


@server.call_tool()
async def call_tool(name: str, arguments: Dict[str, Any]) -> List[TextContent]:
    """处理工具调用"""
    _ensure_dirs()
    
    try:
        if name == "create_plan":
            return await _handle_create_plan(arguments)
        elif name == "read_plan":
            return await _handle_read_plan(arguments)
        elif name == "update_plan":
            return await _handle_update_plan(arguments)
        elif name == "create_spec":
            return await _handle_create_spec(arguments)
        elif name == "read_spec":
            return await _handle_read_spec(arguments)
        elif name == "update_spec":
            return await _handle_update_spec(arguments)
        elif name == "list_plans":
            return await _handle_list_plans(arguments)
        elif name == "list_specs":
            return await _handle_list_specs(arguments)
        elif name == "delete_document":
            return await _handle_delete_document(arguments)
        else:
            raise ValueError(f"未知工具: {name}")
    except Exception as e:
        return [TextContent(
            type="text",
            text=fast_json_dumps({
                "success": False,
                "error": str(e),
                "error_type": type(e).__name__
            }, ensure_ascii=False)
        )]


# ============== Plan 模式处理函数 ==============

async def _handle_create_plan(args: Dict[str, Any]) -> List[TextContent]:
    """创建规划文档"""
    title = args["title"]
    description = args["description"]
    goals = args["goals"]
    steps = args["steps"]
    criteria = args["criteria"]
    notes = args.get("notes", "")
    output_path = args.get("output_path")
    
    # 生成内容
    content = PLAN_TEMPLATE.format(
        title=title,
        description=description,
        goals=goals,
        steps=steps,
        criteria=criteria,
        notes=notes,
        created_at=datetime.now().isoformat()
    )
    
    # 确定输出路径
    if not output_path:
        safe_title = "".join(c if c.isalnum() or c in "-_" else "_" for c in title)
        output_path = os.path.join(PLANS_DIR, f"plan_{safe_title}.md")
    
    if not output_path.endswith('.md'):
        output_path += '.md'
    
    # 验证路径
    output_path = _validate_path(output_path, [PLANS_DIR, SPECS_DIR, "."])
    
    # 确保目录存在
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # 写入文件
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "file_path": output_path,
            "file_name": os.path.basename(output_path),
            "title": title,
            "created_at": datetime.now().isoformat()
        }, ensure_ascii=False, indent=2)
    )]


async def _handle_read_plan(args: Dict[str, Any]) -> List[TextContent]:
    """读取规划文档"""
    plan_path = args["plan_path"]
    
    # 验证路径
    plan_path = _validate_path(plan_path, [PLANS_DIR, SPECS_DIR, "."])
    
    if not os.path.exists(plan_path):
        raise FileNotFoundError(f"规划文件不存在: {plan_path}")
    
    with open(plan_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 解析章节
    sections = _parse_markdown_sections(content)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "file_path": plan_path,
            "file_name": os.path.basename(plan_path),
            "content": content,
            "sections": list(sections.keys()),
            "parsed_sections": sections,
            "size": len(content)
        }, ensure_ascii=False, indent=2)
    )]


async def _handle_update_plan(args: Dict[str, Any]) -> List[TextContent]:
    """更新规划文档"""
    plan_path = args["plan_path"]
    section = args["section"]
    new_content = args["content"]
    
    # 验证路径
    plan_path = _validate_path(plan_path, [PLANS_DIR, SPECS_DIR, "."])
    
    if not os.path.exists(plan_path):
        raise FileNotFoundError(f"规划文件不存在: {plan_path}")
    
    # 读取原内容
    with open(plan_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 更新章节
    updated_content = _update_markdown_section(content, section, new_content)
    
    # 写入文件
    with open(plan_path, 'w', encoding='utf-8') as f:
        f.write(updated_content)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "file_path": plan_path,
            "updated_section": section,
            "updated_at": datetime.now().isoformat()
        }, ensure_ascii=False, indent=2)
    )]


# ============== Spec 模式处理函数 ==============

async def _handle_create_spec(args: Dict[str, Any]) -> List[TextContent]:
    """创建规格文档套装"""
    feature_name = args["feature_name"]
    title = args["title"]
    description = args["description"]
    requirements = args["requirements"]
    technical_design = args.get("technical_design", "待补充")
    interfaces = args.get("interfaces", "待补充")
    acceptance_criteria = args.get("acceptance_criteria", "待补充")
    tasks = args.get("tasks", "待补充")
    
    # 创建功能目录
    feature_dir = os.path.join(SPECS_DIR, feature_name)
    os.makedirs(feature_dir, exist_ok=True)
    
    created_files = []
    created_at = datetime.now().isoformat()
    
    # 1. 创建 spec.md
    spec_content = SPEC_TEMPLATE.format(
        title=title,
        description=description,
        requirements=requirements,
        technical_design=technical_design,
        interfaces=interfaces,
        acceptance_criteria=acceptance_criteria,
        created_at=created_at
    )
    spec_path = os.path.join(feature_dir, "spec.md")
    with open(spec_path, 'w', encoding='utf-8') as f:
        f.write(spec_content)
    created_files.append(spec_path)
    
    # 2. 创建 tasks.md
    tasks_content = TASKS_TEMPLATE.format(
        title=title,
        tasks=tasks,
        dependencies="待补充",
        estimates="待补充",
        created_at=created_at
    )
    tasks_path = os.path.join(feature_dir, "tasks.md")
    with open(tasks_path, 'w', encoding='utf-8') as f:
        f.write(tasks_content)
    created_files.append(tasks_path)
    
    # 3. 创建 checklist.md
    checklist_content = CHECKLIST_TEMPLATE.format(
        title=title,
        prerequisites="- [ ] 需求已确认\n- [ ] 技术方案已评审",
        development="- [ ] 代码实现\n- [ ] 单元测试\n- [ ] 代码审查",
        testing="- [ ] 功能测试\n- [ ] 集成测试\n- [ ] 性能测试",
        deployment="- [ ] 部署文档\n- [ ] 回滚方案",
        documentation="- [ ] API 文档\n- [ ] 用户手册",
        created_at=created_at
    )
    checklist_path = os.path.join(feature_dir, "checklist.md")
    with open(checklist_path, 'w', encoding='utf-8') as f:
        f.write(checklist_content)
    created_files.append(checklist_path)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "feature_name": feature_name,
            "feature_dir": feature_dir,
            "created_files": created_files,
            "file_count": len(created_files),
            "created_at": created_at
        }, ensure_ascii=False, indent=2)
    )]


async def _handle_read_spec(args: Dict[str, Any]) -> List[TextContent]:
    """读取规格文档"""
    spec_path = args["spec_path"]
    
    # 验证路径
    spec_path = _validate_path(spec_path, [PLANS_DIR, SPECS_DIR, "."])
    
    if not os.path.exists(spec_path):
        raise FileNotFoundError(f"规格文件不存在: {spec_path}")
    
    with open(spec_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 解析章节
    sections = _parse_markdown_sections(content)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "file_path": spec_path,
            "file_name": os.path.basename(spec_path),
            "content": content,
            "sections": list(sections.keys()),
            "size": len(content)
        }, ensure_ascii=False, indent=2)
    )]


async def _handle_update_spec(args: Dict[str, Any]) -> List[TextContent]:
    """更新规格文档"""
    spec_path = args["spec_path"]
    section = args["section"]
    new_content = args["content"]
    
    # 验证路径
    spec_path = _validate_path(spec_path, [PLANS_DIR, SPECS_DIR, "."])
    
    if not os.path.exists(spec_path):
        raise FileNotFoundError(f"规格文件不存在: {spec_path}")
    
    # 读取原内容
    with open(spec_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 更新章节
    updated_content = _update_markdown_section(content, section, new_content)
    
    # 写入文件
    with open(spec_path, 'w', encoding='utf-8') as f:
        f.write(updated_content)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "file_path": spec_path,
            "updated_section": section,
            "updated_at": datetime.now().isoformat()
        }, ensure_ascii=False, indent=2)
    )]


# ============== 通用工具函数 ==============

async def _handle_list_plans(args: Dict[str, Any]) -> List[TextContent]:
    """列出规划文件"""
    limit = args.get("limit", 50)
    
    _ensure_dirs()
    
    plans = []
    for filename in os.listdir(PLANS_DIR):
        if filename.endswith('.md'):
            filepath = os.path.join(PLANS_DIR, filename)
            stat = os.stat(filepath)
            
            # 尝试读取标题
            title = filename
            try:
                with open(filepath, 'r', encoding='utf-8') as f:
                    first_line = f.readline()
                    if first_line.startswith('# '):
                        title = first_line[2:].strip()
            except:
                pass
            
            plans.append({
                "filename": filename,
                "title": title,
                "path": filepath,
                "size": stat.st_size,
                "modified": datetime.fromtimestamp(stat.st_mtime).isoformat()
            })
    
    # 按修改时间排序
    plans.sort(key=lambda x: x["modified"], reverse=True)
    plans = plans[:limit]
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "count": len(plans),
            "plans": plans
        }, ensure_ascii=False, indent=2)
    )]


async def _handle_list_specs(args: Dict[str, Any]) -> List[TextContent]:
    """列出规格文档目录"""
    _ensure_dirs()
    
    specs = []
    if os.path.exists(SPECS_DIR):
        for dirname in os.listdir(SPECS_DIR):
            dirpath = os.path.join(SPECS_DIR, dirname)
            if os.path.isdir(dirpath):
                # 检查是否有 spec.md
                spec_file = os.path.join(dirpath, "spec.md")
                has_spec = os.path.exists(spec_file)
                
                # 统计文件数量
                file_count = len([f for f in os.listdir(dirpath) if f.endswith('.md')])
                
                specs.append({
                    "feature_name": dirname,
                    "path": dirpath,
                    "has_spec": has_spec,
                    "file_count": file_count
                })
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "count": len(specs),
            "specs": specs
        }, ensure_ascii=False, indent=2)
    )]


async def _handle_delete_document(args: Dict[str, Any]) -> List[TextContent]:
    """删除文档"""
    doc_path = args["doc_path"]
    
    # 验证路径
    doc_path = _validate_path(doc_path, [PLANS_DIR, SPECS_DIR, "."])
    
    if not os.path.exists(doc_path):
        raise FileNotFoundError(f"文档不存在: {doc_path}")
    
    os.remove(doc_path)
    
    return [TextContent(
        type="text",
        text=fast_json_dumps({
            "success": True,
            "deleted": doc_path,
            "deleted_at": datetime.now().isoformat()
        }, ensure_ascii=False, indent=2)
    )]


# ============== 辅助函数 ==============

def _parse_markdown_sections(content: str) -> Dict[str, str]:
    """解析 markdown 章节"""
    sections = {}
    current_section = None
    current_content = []

    # 统一处理换行符
    content = content.replace('\r\n', '\n')

    for line in content.split('\n'):
        # 去除行尾空白用于判断
        clean_line = line.rstrip()
        if clean_line.startswith('## '):
            # 保存上一个章节
            if current_section:
                sections[current_section] = '\n'.join(current_content).strip()
            # 开始新章节
            current_section = clean_line[3:].strip()
            current_content = []
        elif current_section:
            current_content.append(line)

    # 保存最后一个章节
    if current_section:
        sections[current_section] = '\n'.join(current_content).strip()

    return sections


def _update_markdown_section(content: str, section_name: str, new_content: str) -> str:
    """更新 markdown 章节内容"""
    # 统一处理换行符
    content = content.replace('\r\n', '\n')
    lines = content.split('\n')
    result = []
    in_target_section = False
    section_updated = False

    for line in lines:
        # 去除行尾空白用于判断
        clean_line = line.rstrip()
        if clean_line.startswith('## '):
            # 如果之前在目标章节，保存新内容
            if in_target_section and not section_updated:
                result.append(new_content)
                section_updated = True

            # 检查是否是目标章节
            if clean_line[3:].strip() == section_name:
                in_target_section = True
                result.append(line)
            else:
                in_target_section = False
                result.append(line)
        elif in_target_section:
            # 在目标章节内，跳过旧内容（除了标题）
            continue
        else:
            result.append(line)

    # 如果目标章节是最后一个
    if in_target_section and not section_updated:
        result.append(new_content)

    return '\n'.join(result)


# ============== 启动函数 ==============

async def main():
    """启动 MCP Server（Windows 兼容版）"""
    import platform
    
    _ensure_dirs()
    
    # Windows 环境设置
    if platform.system() == "Windows":
        asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    
    from mcp.server.stdio import stdio_server as mcp_stdio_server
    
    async with mcp_stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())