"""Plan/Spec 模式集成测试

测试 MCP 服务与 decision_chain 的集成，
验证完整的 plan/spec 工作流程。
"""

import json
import os
import sys
import tempfile
import shutil
from pathlib import Path


# 模板定义（直接从 MCP server 复制）
PLAN_TEMPLATE = """# {title}

## 概述

{description}

## 目标

{goals}

## 实施步骤

{steps}

## 验收标准

{criteria}

## 备注

{notes}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""

SPEC_TEMPLATE = """# {title} - 规格文档

## 概述

{description}

## 功能需求

{requirements}

## 技术方案

{technical_design}

## 接口定义

{interfaces}

## 验收标准

{acceptance_criteria}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""

TASKS_TEMPLATE = """# {title} - 任务列表

## 任务分解

{tasks}

## 依赖关系

{dependencies}

## 时间估算

{estimates}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""

CHECKLIST_TEMPLATE = """# {title} - 检查清单

## 前置条件

{prerequisites}

## 开发检查项

{development}

## 测试检查项

{testing}

## 部署检查项

{deployment}

## 文档检查项

{documentation}

---
*Generated by DecisionChain MCP Server*
*Created: {created_at}*
"""


def _parse_markdown_sections(content: str) -> dict:
    """解析 markdown 章节"""
    sections = {}
    current_section = None
    current_content = []

    for line in content.split('\n'):
        if line.startswith('## '):
            # 保存上一个章节
            if current_section:
                sections[current_section] = '\n'.join(current_content).strip()
            # 开始新章节
            current_section = line[3:].strip()
            current_content = []
        elif current_section:
            current_content.append(line)

    # 保存最后一个章节
    if current_section:
        sections[current_section] = '\n'.join(current_content).strip()

    return sections


def _update_markdown_section(content: str, section_name: str, new_content: str) -> str:
    """更新 markdown 章节内容"""
    # 统一处理换行符
    content = content.replace('\r\n', '\n')
    lines = content.split('\n')
    result = []
    in_target_section = False
    section_updated = False

    for line in lines:
        # 去除行尾换行符用于判断
        clean_line = line.rstrip()
        if clean_line.startswith('## '):
            # 如果之前在目标章节，保存新内容
            if in_target_section and not section_updated:
                result.append(new_content)
                section_updated = True

            # 检查是否是目标章节
            if clean_line[3:].strip() == section_name:
                in_target_section = True
                result.append(line)
            else:
                in_target_section = False
                result.append(line)
        elif in_target_section:
            # 在目标章节内，跳过旧内容（除了标题）
            continue
        else:
            result.append(line)

    # 如果目标章节是最后一个
    if in_target_section and not section_updated:
        result.append(new_content)

    return '\n'.join(result)


class TestPlanSpecIntegration:
    """Plan/Spec 集成测试"""

    def setup_method(self):
        """测试前置准备"""
        self.test_dir = tempfile.mkdtemp()
        self.plans_dir = os.path.join(self.test_dir, "plans")
        self.specs_dir = os.path.join(self.test_dir, ".trae", "specs")
        os.makedirs(self.plans_dir, exist_ok=True)
        os.makedirs(self.specs_dir, exist_ok=True)

    def teardown_method(self):
        """测试后置清理"""
        shutil.rmtree(self.test_dir, ignore_errors=True)

    def test_plan_template_rendering(self):
        """测试规划模板渲染"""
        print("\n=== 测试规划模板渲染 ===")

        # 模拟模板渲染
        plan_content = PLAN_TEMPLATE.format(
            title="洪水预警系统优化规划",
            description="提升洪水预警的准确性和响应速度",
            goals="- 预警准确率提升至95%\n- 响应时间缩短至5分钟",
            steps="1. 数据接入优化\n2. 模型训练\n3. 系统集成",
            criteria="- 通过压力测试\n- 用户验收通过",
            notes="需要在汛期前完成",
            created_at="2026-03-26T10:00:00Z"
        )

        # 验证内容
        assert "洪水预警系统优化规划" in plan_content
        assert "提升洪水预警的准确性和响应速度" in plan_content
        assert "预警准确率提升至95%" in plan_content
        assert "数据接入优化" in plan_content
        assert "通过压力测试" in plan_content

        # 验证章节结构
        sections = _parse_markdown_sections(plan_content)
        assert "概述" in sections
        assert "目标" in sections
        assert "实施步骤" in sections
        assert "验收标准" in sections
        assert "备注" in sections

        print("✓ 规划模板渲染成功")
        print(f"✓ 解析到 {len(sections)} 个章节")

    def test_spec_template_rendering(self):
        """测试规格模板渲染"""
        print("\n=== 测试规格模板渲染 ===")

        # 渲染 spec.md
        spec_content = SPEC_TEMPLATE.format(
            title="洪水预警系统V2",
            description="新一代洪水预警系统，支持多源数据融合",
            requirements="- 支持雷达、卫星、站点数据\n- 预警准确率≥95%",
            technical_design="采用微服务架构，使用机器学习模型",
            interfaces="REST API + WebSocket推送",
            acceptance_criteria="- 功能测试通过率100%\n- 性能测试达标",
            created_at="2026-03-26T10:00:00Z"
        )

        # 验证内容
        assert "洪水预警系统V2" in spec_content
        assert "支持雷达、卫星、站点数据" in spec_content
        assert "微服务架构" in spec_content

        # 验证章节
        sections = _parse_markdown_sections(spec_content)
        assert "概述" in sections
        assert "功能需求" in sections
        assert "技术方案" in sections
        assert "接口定义" in sections
        assert "验收标准" in sections

        print("✓ 规格模板渲染成功")
        print(f"✓ 解析到 {len(sections)} 个章节")

    def test_tasks_template_rendering(self):
        """测试任务模板渲染"""
        print("\n=== 测试任务模板渲染 ===")

        tasks_content = TASKS_TEMPLATE.format(
            title="洪水预警系统V2",
            tasks="- [ ] 数据接入模块\n- [ ] 预警算法模块\n- [ ] 消息推送模块",
            dependencies="数据接入 -> 预警算法 -> 消息推送",
            estimates="- 数据接入: 5天\n- 预警算法: 10天\n- 消息推送: 3天",
            created_at="2026-03-26T10:00:00Z"
        )

        # 验证内容
        assert "数据接入模块" in tasks_content
        assert "预警算法模块" in tasks_content
        assert "消息推送模块" in tasks_content

        # 验证章节
        sections = _parse_markdown_sections(tasks_content)
        assert "任务分解" in sections
        assert "依赖关系" in sections
        assert "时间估算" in sections

        print("✓ 任务模板渲染成功")

    def test_checklist_template_rendering(self):
        """测试检查清单模板渲染"""
        print("\n=== 测试检查清单模板渲染 ===")

        checklist_content = CHECKLIST_TEMPLATE.format(
            title="洪水预警系统V2",
            prerequisites="- [ ] 需求已确认\n- [ ] 技术方案已评审",
            development="- [ ] 代码实现\n- [ ] 单元测试",
            testing="- [ ] 功能测试\n- [ ] 集成测试",
            deployment="- [ ] 部署文档\n- [ ] 回滚方案",
            documentation="- [ ] API文档\n- [ ] 用户手册",
            created_at="2026-03-26T10:00:00Z"
        )

        # 验证内容
        assert "需求已确认" in checklist_content
        assert "代码实现" in checklist_content
        assert "功能测试" in checklist_content

        # 验证章节
        sections = _parse_markdown_sections(checklist_content)
        assert "前置条件" in sections
        assert "开发检查项" in sections
        assert "测试检查项" in sections
        assert "部署检查项" in sections
        assert "文档检查项" in sections

        print("✓ 检查清单模板渲染成功")

    def test_section_update(self):
        """测试章节更新功能"""
        print("\n=== 测试章节更新功能 ===")

        # 使用简单的一行内容测试
        original_content = "# 测试规划\n\n## 概述\n\n原始概述\n\n## 目标\n\n- 目标1\n\n## 实施步骤\n\n旧内容\n"

        # 更新"实施步骤"章节
        new_steps = "新步骤内容"
        updated_content = _update_markdown_section(
            original_content, "实施步骤", new_steps
        )

        # 验证更新
        assert "新步骤内容" in updated_content
        assert "旧内容" not in updated_content

        # 验证其他章节未被修改
        assert "原始概述" in updated_content
        assert "目标1" in updated_content

        print("✓ 章节更新功能正常")

    def test_full_workflow(self):
        """测试完整工作流程"""
        print("\n=== 测试完整工作流程 ===")

        # 1. 创建规划
        plan_data = {
            "title": "洪水预警系统V3升级规划",
            "description": "全面升级洪水预警系统，引入大模型技术",
            "goals": "- 预警准确率提升至98%\n- 误报率降低至2%\n- 响应时间缩短至3分钟",
            "steps": """1. **需求调研与分析**（第1-2周）
   - 调研现有系统问题
   - 收集用户需求
   - 输出需求文档

2. **技术方案设计**（第3-4周）
   - 架构设计
   - 算法选型
   - 接口设计

3. **系统开发**（第5-10周）
   - 核心模块开发
   - 接口实现
   - 单元测试

4. **系统集成与测试**（第11-12周）
   - 集成测试
   - 性能测试
   - 用户验收测试

5. **部署上线**（第13周）
   - 生产环境部署
   - 监控配置
   - 用户培训""",
            "criteria": """- [ ] 预警准确率≥98%（基于历史数据测试）
- [ ] 系统响应时间≤3分钟
- [ ] 并发处理能力≥1000 QPS
- [ ] 用户满意度≥90%
- [ ] 通过安全渗透测试""",
            "notes": "项目需在汛期前（6月）完成上线"
        }

        # 渲染规划文档
        plan_content = PLAN_TEMPLATE.format(
            title=plan_data["title"],
            description=plan_data["description"],
            goals=plan_data["goals"],
            steps=plan_data["steps"],
            criteria=plan_data["criteria"],
            notes=plan_data["notes"],
            created_at="2026-03-26T10:00:00Z"
        )

        # 保存规划文档
        plan_path = os.path.join(self.plans_dir, "flood_warning_v3_plan.md")
        with open(plan_path, 'w', encoding='utf-8') as f:
            f.write(plan_content)

        print(f"✓ 规划文档已创建: {plan_path}")

        # 2. 基于规划创建规格
        feature_name = "flood-warning-v3"
        spec_dir = os.path.join(self.specs_dir, feature_name)
        os.makedirs(spec_dir, exist_ok=True)

        # 渲染规格文档
        spec_content = SPEC_TEMPLATE.format(
            title="洪水预警系统V3",
            description="基于大模型的智能洪水预警系统",
            requirements="""### 功能需求1：多源数据融合
- **需求描述**：整合雷达、卫星、站点等多源数据
- **输入**：雷达图像、卫星云图、站点观测数据
- **输出**：融合后的统一数据格式
- **约束**：数据延迟≤5分钟
- **优先级**：P0

### 功能需求2：智能预警生成
- **需求描述**：基于大模型生成预警文本和调度建议
- **输入**：融合后的数据
- **输出**：预警等级、影响范围、调度建议
- **约束**：生成时间≤30秒
- **优先级**：P0""",
            technical_design="""### 架构设计
采用微服务架构，核心组件包括：
- 数据采集服务
- 数据融合服务
- 预警生成服务（基于LLM）
- 消息推送服务

### 核心算法
- 数据融合：时空插值算法
- 预警生成：基于RAG的大模型应用""",
            interfaces="""### API 接口
| 方法 | 路径 | 描述 | 请求参数 | 响应数据 |
|------|------|------|----------|----------|
| POST | /api/v3/warning | 生成预警 | {"data": {...}} | {"warning": {...}} |
| GET | /api/v3/status | 获取状态 | - | {"status": "ok"} |""",
            acceptance_criteria="""- [ ] 数据融合准确率≥95%
- [ ] 预警生成时间≤30秒
- [ ] API可用性≥99.9%
- [ ] 系统吞吐量≥1000 QPS""",
            created_at="2026-03-26T10:00:00Z"
        )

        spec_path = os.path.join(spec_dir, "spec.md")
        with open(spec_path, 'w', encoding='utf-8') as f:
            f.write(spec_content)

        print(f"✓ 规格文档已创建: {spec_path}")

        # 3. 创建任务列表
        tasks_content = TASKS_TEMPLATE.format(
            title="洪水预警系统V3",
            tasks="""- [ ] **TASK-001**：数据采集模块开发
  - 预估工时：5天
  - 负责人：开发组A
  - 依赖：无
  - 验收：数据接入正常

- [ ] **TASK-002**：数据融合算法实现
  - 预估工时：7天
  - 负责人：算法组
  - 依赖：TASK-001
  - 验收：融合准确率达标

- [ ] **TASK-003**：预警生成服务开发
  - 预估工时：10天
  - 负责人：开发组B
  - 依赖：TASK-002
  - 验收：预警生成正常""",
            dependencies="TASK-001 -> TASK-002 -> TASK-003",
            estimates="总工期：约12周",
            created_at="2026-03-26T10:00:00Z"
        )

        tasks_path = os.path.join(spec_dir, "tasks.md")
        with open(tasks_path, 'w', encoding='utf-8') as f:
            f.write(tasks_content)

        print(f"✓ 任务列表已创建: {tasks_path}")

        # 4. 创建检查清单
        checklist_content = CHECKLIST_TEMPLATE.format(
            title="洪水预警系统V3",
            prerequisites="- [ ] 需求已确认并评审通过\n- [ ] 技术方案已评审通过",
            development="- [ ] 代码实现完成\n- [ ] 单元测试覆盖率≥80%",
            testing="- [ ] 功能测试通过\n- [ ] 性能测试达标",
            deployment="- [ ] 部署文档完成\n- [ ] 回滚方案准备",
            documentation="- [ ] API文档更新\n- [ ] 用户手册编写",
            created_at="2026-03-26T10:00:00Z"
        )

        checklist_path = os.path.join(spec_dir, "checklist.md")
        with open(checklist_path, 'w', encoding='utf-8') as f:
            f.write(checklist_content)

        print(f"✓ 检查清单已创建: {checklist_path}")

        # 5. 验证文件
        assert os.path.exists(plan_path)
        assert os.path.exists(spec_path)
        assert os.path.exists(tasks_path)
        assert os.path.exists(checklist_path)

        # 6. 读取并验证内容
        with open(plan_path, 'r', encoding='utf-8') as f:
            saved_plan = f.read()

        sections = _parse_markdown_sections(saved_plan)
        assert len(sections) >= 4

        print(f"✓ 完整工作流测试通过")
        print(f"  - 规划文档: {len(saved_plan)} 字符")
        print(f"  - 规格套装: 3个文件")

    def test_manual_editing_simulation(self):
        """测试手工编辑模拟"""
        print("\n=== 测试手工编辑模拟 ===")

        # 创建初始文档
        doc_path = os.path.join(self.plans_dir, "editable_plan.md")
        initial_content = """# 可编辑规划

## 概述

初始概述内容

## 目标

- 初始目标

## 实施步骤

1. 初始步骤
"""

        with open(doc_path, 'w', encoding='utf-8') as f:
            f.write(initial_content)

        # 模拟手工编辑：更新"目标"章节
        with open(doc_path, 'r', encoding='utf-8') as f:
            content = f.read()

        new_goals = """- 目标1：具体目标描述
- 目标2：具体目标描述
- 目标3：具体目标描述"""

        updated_content = _update_markdown_section(content, "目标", new_goals)

        # 保存更新
        with open(doc_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)

        # 验证更新
        with open(doc_path, 'r', encoding='utf-8') as f:
            saved_content = f.read()

        assert "目标1" in saved_content
        assert "目标3" in saved_content
        assert "初始目标" not in saved_content

        print("✓ 手工编辑模拟成功")

    def test_plan_prompt_content(self):
        """测试规划提示词内容"""
        print("\n=== 测试规划提示词内容 ===")

        # 模拟提示词生成
        user_input = "为水库调度系统制定优化规划"
        domain = "水利调度"
        constraints = {
            "time_limit": "3个月",
            "budget": "100万",
            "team_size": 5
        }

        # 构建提示词（模拟 PlanSpecPrompts.get_plan_generation_prompt）
        prompt = f"""【任务】
请根据以下需求生成一份专业的项目规划文档。

【用户输入】
{user_input}

【领域背景】
{domain}

【约束条件】
{json.dumps(constraints, ensure_ascii=False, indent=2)}

【输出要求】
请按以下 Markdown 格式生成规划文档：

【质量要求】
1. 目标必须遵循 SMART 原则（具体、可衡量、可达成、相关、有时限）
2. 步骤必须逻辑清晰、可执行，每个步骤都有明确的交付物
3. 验收标准必须可验证，使用检查清单形式
4. 考虑项目风险并提供应对策略
5. 使用专业术语，符合水利行业规范"""

        # 验证提示词内容
        assert "水库调度系统" in prompt
        assert "水利调度" in prompt
        assert "3个月" in prompt
        assert "100万" in prompt
        assert "SMART" in prompt

        print("✓ 规划提示词内容验证成功")
        print(f"✓ 提示词长度: {len(prompt)} 字符")

    def test_spec_prompt_content(self):
        """测试规格提示词内容"""
        print("\n=== 测试规格提示词内容 ===")

        # 基于规划内容生成规格
        plan_content = """# 水库调度系统优化规划

## 概述
引入AI技术优化水库调度决策

## 目标
- 调度效率提升30%
- 人工成本降低50%

## 实施步骤
1. 需求分析
2. 方案设计
3. 开发实施

## 验收标准
- 系统稳定运行
- 用户培训完成
"""

        # 模拟提示词生成
        prompt = f"""【任务】
请根据以下需求生成一份完整的技术规格文档套装（spec.md、tasks.md、checklist.md）。

【用户输入】
基于规划生成详细技术规格

【领域背景】
水利调度

【现有规划内容】
{plan_content}

【输出要求】
请生成以下三个文档的内容：

### 1. spec.md - 规格文档
### 2. tasks.md - 任务列表
### 3. checklist.md - 检查清单

【质量要求】
1. 需求必须完整、无歧义，使用用户故事格式
2. 技术方案必须可行，包含架构图和关键算法
3. 接口定义必须规范，包含请求/响应示例
4. 性能指标必须具体、可测试"""

        # 验证提示词
        assert "水库调度系统优化规划" in prompt
        assert "spec.md" in prompt
        assert "tasks.md" in prompt
        assert "checklist.md" in prompt

        print("✓ 规格提示词内容验证成功")
        print(f"✓ 提示词长度: {len(prompt)} 字符")


def run_all_tests():
    """运行所有测试"""
    print("=" * 60)
    print("Plan/Spec 模式集成测试")
    print("=" * 60)

    test = TestPlanSpecIntegration()

    try:
        # 运行所有测试方法
        test.setup_method()
        test.test_plan_template_rendering()
        test.teardown_method()

        test.setup_method()
        test.test_spec_template_rendering()
        test.teardown_method()

        test.setup_method()
        test.test_tasks_template_rendering()
        test.teardown_method()

        test.setup_method()
        test.test_checklist_template_rendering()
        test.teardown_method()

        test.setup_method()
        test.test_section_update()
        test.teardown_method()

        test.setup_method()
        test.test_full_workflow()
        test.teardown_method()

        test.setup_method()
        test.test_manual_editing_simulation()
        test.teardown_method()

        test.setup_method()
        test.test_plan_prompt_content()
        test.teardown_method()

        test.setup_method()
        test.test_spec_prompt_content()
        test.teardown_method()

        print("\n" + "=" * 60)
        print("✓ 所有集成测试通过！")
        print("=" * 60)

    except Exception as e:
        print(f"\n✗ 测试失败: {e}")
        import traceback
        traceback.print_exc()
        return False

    return True


if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)
