"""全局常量定义"""

# 应用信息
APP_NAME = "flood_decision_agent"
APP_VERSION = "0.1.0"
APP_DESCRIPTION = "洪水调度决策智能体"

# 超时配置
DEFAULT_TIMEOUT = 60  # 秒
MAX_RETRY_ATTEMPTS = 3
RETRY_BACKOFF_FACTOR = 2

# 对话配置
MAX_CONVERSATION_HISTORY = 50
CONTEXT_WINDOW_SIZE = 128000
SESSION_TIMEOUT = 3600  # 1小时

# 管道配置
MAX_PIPELINE_ITERATIONS = 10
PIPELINE_TIMEOUT = 300  # 5分钟

# MCP 配置
MCP_CONNECTION_TIMEOUT = 30
MCP_RETRY_ATTEMPTS = 3

# 评估配置
EVALUATION_THRESHOLD_EXCELLENT = 90
EVALUATION_THRESHOLD_GOOD = 75
EVALUATION_THRESHOLD_ACCEPTABLE = 60

# 文件路径
DEFAULT_DATA_DIR = "resources/data"
DEFAULT_DOCUMENTS_DIR = "resources/documents"
DEFAULT_PROMPTS_DIR = "resources/prompts"
